server:
  port: 8080

spring:
  application:
    name: there

  datasource:
    url: jdbc:mysql://there-db.cjg8pisspmbh.ap-northeast-2.rds.amazonaws.com:3306/There
    username: There
    password: therezzang!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql

  redis:
    port: 6379
    host: recordinthere.shop
  jwt:
    secret-key: SECRET_KEY
    blacklist:
      access-token: BlackList_AccessToken_

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2e8b184b25eb6aee0a1496b4af1d7ffd
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/users/oauth/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
cloud:
  aws:
    credentials:
      access-key: AKIAVAK5CW4BGAC4XVWQ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: there-s3-bucket
    stack:
      auto: false