server:
  port: 8080

spring:
  application:
    name: there

  datasource:
    url: jdbc:mysql://there-db.cjg8pisspmbh.ap-northeast-2.rds.amazonaws.com:3306/There
    username: There
    password: therezzang!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql

cloud:
  aws:
    credentials:
      access-key: AKIAVAK5CW4BIA6USF4O
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: there-s3-bucket
    stack:
      auto: false